jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Run Spotless check
      run: mvn spotless:check
    - continue-on-error: true
      name: Run unit tests
      run: mvn test
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yaml
